### ISSUE TITLE
This isn't evil, it's pure brilliance! :D

### ISSUE THREAD

**Issue by Tcll** [solus-project/fpi#1]
might want to fix that in your readme ;D

with this, I'll be able to:
- install Nemo which is unarguably the best File Manager, far superior to Nautilus, and used by Mint.
- install XFCE, which is arguably the absolute best Desktop Environment.

**Comment by ikeydoherty** [comment]
No you won't - they're too large and complex and have binary deps not present in Solus.

fpi likely won't need to exist anymore with the advent of snaps and flatpaks

**Comment by Tcll** [comment]
![](http://pre08.deviantart.net/d335/th/pre/f/2011/288/c/2/okay_by_rober_raik-d4cw242.png)

**Comment by ikeydoherty** [comment]
FWIW it was explicitly noted when we first started this project it would only be for corner case software and not complex stacks :)

**Comment by Tcll** [comment]
may I request Nemo and XFCE at least?? :)
